name: monopoly_deal_app
x-environment: &environment
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  POSTGRES_DB: ${POSTGRES_DB}
  PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
  PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
  WEB_PORT: ${WEB_PORT:-8001}

networks:
  monopoly_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

services:
  tox:
    build:
      context: .
      dockerfile: Docker/Dockerfile
    working_dir: /app
    depends_on:
      database_service:
        condition: service_completed_successfully
    command: tox


  database_service:
    build:
      context: .
      dockerfile: Docker/Dockerfile.database
    pull_policy: build
    container_name: monopoly_database_service
    networks:
      monopoly_network:
        ipv4_address: 172.20.0.10
    environment:
      <<: *environment
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    working_dir: /app

  web:
    build:
      context: .
      dockerfile: Docker/Dockerfile
    pull_policy: build
    container_name: monopoly_web
    ports:
      - "${WEB_PORT:-8001}:8000"
    networks:
      monopoly_network:
        ipv4_address: 172.20.0.11
    environment:
      <<: *environment
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
      database_service:
        condition: service_completed_successfully

  db:
    image: postgres:16
    container_name: monopoly_postgres
    environment:
      <<: *environment
    ports:
      - "5434:5432"
    networks:
      monopoly_network:
        ipv4_address: 172.20.0.12
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  pgadmin:
    image: dpage/pgadmin4:9.6
    container_name: monopoly_pgadmin
    environment:
      <<: *environment
    ports:
      - "5050:80"
    networks:
      monopoly_network:
        ipv4_address: 172.20.0.13
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  pgdata:
  pgadmin_data:
